# Generated by Django 5.2.13 on 2026-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('immagine', models.ImageField(upload_to='opere/')),
                ('citazione_breve', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('ordine', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Opere',
                'ordering': ['ordine'],
            },
        ),
    ]
